'use strict';

/**
 * src/services/authOtp.service.js
 *
 * OTP login. Kept separate from auth.service.js so the password flow and the
 * OTP flow can evolve independently — customers and drivers use OTP, staff use
 * passwords.
 *
 * ---------------------------------------------------------------------------
 * THE IDENTIFIER: PHONE (SMS), OR EMAIL
 * ---------------------------------------------------------------------------
 * Riders sign in with their MOBILE NUMBER and receive the code by SMS. Email
 * is still accepted, for clients not yet updated (the driver app) and for
 * accounts with no phone; the code then goes to that inbox.
 *
 * Phone lookups used to be avoided because users.phone was not unique. It is
 * now (20260924140000_unique_phone) — but uniqueness is on the STORED STRING,
 * and registration historically stored numbers exactly as typed. The same
 * person can therefore be on file as "+91 98765 43210", "09876543210" or
 * "9876543210", and an exact-match lookup would tell them they have no
 * account. findAccountByPhone compares the last ten DIGITS instead, which
 * matches every one of those spellings without rewriting stored data.
 *
 * If that comparison finds TWO accounts — one number spelled two ways on two
 * rows — the login refuses rather than guessing. Sending one person's code to
 * a session for someone else's account is the failure this whole design
 * exists to prevent.
 *
 * ---------------------------------------------------------------------------
 * ACCOUNT-CREATION POLICY
 * ---------------------------------------------------------------------------
 * Receiving a code proves control of a mailbox and nothing more, so an OTP
 * login can only ever authenticate an existing USER or DRIVER. It never creates
 * an account, and staff roles are assigned by an admin — never earned by
 * receiving a message.
 */

const otpService = require('./otp.service');
const smsService = require('./sms.service');
const tokens = require('../utils/tokens');
const { prisma } = require('../config/prisma');
const { ApiError, publicUser } = require('../utils/helpers');

/* ------------------------------------------------------------------ *
 * Account lookup
 * ------------------------------------------------------------------ */

/** Generated by phone-first signup to satisfy UNIQUE(email). Cannot receive mail. */
const isPlaceholderEmail = (email) =>
  String(email || '').toLowerCase().endsWith('@placeholder.local');

/**
 * Resolve the login identifier to an account.
 *
 * Both steps of the flow go through here so they cannot disagree. If request
 * and verify resolved differently, a code could be mailed to one account and a
 * session issued for another — a broken login at best, account takeover at
 * worst.
 *
 * The address is lower-cased defensively. The zod schema already does this, but
 * this service is also reachable from scripts and future callers, and a
 * case-sensitive UNIQUE column turns a missed toLowerCase() into "your account
 * does not exist".
 */
async function findAccountByEmail(rawEmail) {
  const email = String(rawEmail || '').trim().toLowerCase();
  if (!email) return null;

  return prisma.user.findFirst({
    where: { email, role: { in: ['USER', 'DRIVER'] } },
  });
}

/**
 * Resolve a mobile number to exactly one USER/DRIVER account, matching on the
 * last ten digits of what is stored (see the header for why).
 *
 * @returns {Promise<object|null>} the user, or null when none match
 * @throws PHONE_AMBIGUOUS when more than one account matches
 */
async function findAccountByPhone(rawPhone) {
  const mobile = smsService.indianMobile(rawPhone);
  if (!mobile) return null;

  // Raw SQL because the comparison is on a NORMALISED column value, which
  // Prisma's query builder cannot express. `mobile` is a bound parameter.
  // LIMIT 2: all we need to know is "one" or "more than one".
  const rows = await prisma.$queryRaw`
    SELECT id FROM users
    WHERE phone IS NOT NULL
      AND right(regexp_replace(phone, '[^0-9]', '', 'g'), 10) = ${mobile}
      AND role IN ('USER', 'DRIVER')
    LIMIT 2
  `;

  if (rows.length === 0) return null;
  if (rows.length > 1) {
    throw ApiError.conflict(
      'This mobile number is linked to more than one account. Please contact support.',
      'PHONE_AMBIGUOUS',
    );
  }
  return prisma.user.findUnique({ where: { id: rows[0].id } });
}

/** Phone wins when both are sent — it is the identifier the rider app uses. */
async function findAccount({ phone, email } = {}) {
  if (phone) return findAccountByPhone(phone);
  if (email) return findAccountByEmail(email);
  return null;
}

/* ------------------------------------------------------------------ *
 * Request
 * ------------------------------------------------------------------ */

/**
 * Sends a code — but ONLY to addresses that already have an account. This app
 * is registration-gated: an unknown address is refused with NOT_REGISTERED so
 * the client can send the person to sign up first. (This deliberately reveals
 * whether an address is registered, which is the intended product behaviour
 * here. If that ever changes, return a generic reply the way
 * passwordReset.service.js does.)
 */
async function requestOtp({ phone, email } = {}) {
  const byPhone = Boolean(phone);
  const existing = await findAccount({ phone, email });

  if (!existing) {
    throw ApiError.notFound(
      byPhone
        ? 'No account found for this mobile number. Please register first.'
        : 'No account found for this email. Please register first.',
      'NOT_REGISTERED',
    );
  }

  if (!existing.isActive) {
    throw ApiError.forbidden('Your account has been deactivated', 'ACCOUNT_INACTIVE');
  }

  // A phone-first account carries a generated phone_<number>@placeholder.local
  // address. It can never receive mail, so it is never offered as a channel.
  const realEmail = isPlaceholderEmail(existing.email) ? null : existing.email;

  // An EMAIL login must have a deliverable address — that is where the rider
  // is looking for the code. A PHONE login does not need one: the code goes
  // by SMS, and a real address is only the fallback if SMS fails.
  if (!byPhone && !realEmail) {
    throw ApiError.badRequest(
      'This account has no usable email address. Sign in with your mobile number instead.',
      'NO_EMAIL_ON_ACCOUNT',
    );
  }

  // Keyed by ACCOUNT ID, not by the typed identifier: the Redis attempt
  // counter, cooldown and daily cap follow the account, and cannot be reset by
  // switching between phone and email or by respelling either.
  const result = await otpService.requestOtp(existing.id, {
    // Only a phone login is delivered by SMS. An email login keeps going to
    // the inbox the person just typed, which is where they are looking.
    phone: byPhone ? existing.phone : null,
    email: realEmail,
    name: existing.name,
  });

  let message = 'A verification code has been sent';
  if (result.channel === 'sms') message = `A verification code has been sent by SMS to ${result.sentTo}`;
  else if (result.sentTo) message = `A verification code has been sent to ${result.sentTo}`;

  return { ...result, message };
}

/* ------------------------------------------------------------------ *
 * Verify → log in
 * ------------------------------------------------------------------ */

async function verifyAndLogin({ phone, email, code }, meta = {}) {
  let user;
  try {
    user = await findAccount({ phone, email });
  } catch (err) {
    // An ambiguous number never had a code issued (requestOtp refused it),
    // so report it the same way as any other code that cannot match.
    if (err?.code === 'PHONE_AMBIGUOUS') user = null;
    else throw err;
  }

  // Resolved BEFORE the code is checked, because the code is stored under the
  // account id. No account means there is no bucket to check against, so this
  // is reported as an invalid code rather than a missing account — otherwise
  // this step would fail differently for registered and unregistered addresses
  // and become a way to test which ones exist.
  if (!user) {
    throw ApiError.unauthorized('Code is invalid or has expired', 'OTP_INVALID');
  }

  // Throws on wrong/expired/locked. Consumes the code on success.
  await otpService.verifyOtp(user.id, code);

  if (!user.isActive) {
    throw ApiError.forbidden('Your account has been deactivated', 'ACCOUNT_INACTIVE');
  }

  const accessToken = tokens.signAccessToken({ userId: user.id, role: user.role });
  const refreshToken = tokens.signRefreshToken({ userId: user.id });

  await prisma.refreshToken.create({
    data: {
      userId: user.id,
      tokenHash: tokens.hashToken(refreshToken),
      expiresAt: tokens.refreshExpiryDate(),
      userAgent: (meta.userAgent || '').slice(0, 255) || null,
      ip: (meta.ip || '').slice(0, 45) || null,
    },
  });

  return { user: publicUser(user), accessToken, refreshToken };
}

module.exports = { requestOtp, verifyAndLogin, findAccountByPhone };