'use strict';

/**
 * src/services/authOtp.service.js
 *
 * OTP login. Kept separate from auth.service.js so the password flow and the
 * OTP flow can evolve independently — customers and drivers use OTP, staff use
 * passwords.
 *
 * ---------------------------------------------------------------------------
 * WHY EMAIL IS THE IDENTIFIER
 * ---------------------------------------------------------------------------
 * users.email is UNIQUE; users.phone is only INDEXED. A phone lookup can match
 * several rows — an admin-created DRIVER and a self-registered USER commonly
 * share a number — which leaves the login guessing which account the person
 * meant. An email lookup matches exactly one row or none, so the account the
 * code is sent to is provably the account the session is issued for.
 *
 * It also lines up with delivery: the code goes to an inbox, so asking for the
 * address of that inbox is the one thing the user can actually verify.
 *
 * ---------------------------------------------------------------------------
 * ACCOUNT-CREATION POLICY
 * ---------------------------------------------------------------------------
 * Receiving a code proves control of a mailbox and nothing more, so an OTP
 * login can only ever authenticate an existing USER or DRIVER. It never creates
 * an account, and staff roles are assigned by an admin — never earned by
 * receiving a message.
 */

const otpService = require('./otp.service');
const tokens = require('../utils/tokens');
const { prisma } = require('../config/prisma');
const { ApiError, publicUser } = require('../utils/helpers');

/* ------------------------------------------------------------------ *
 * Account lookup
 * ------------------------------------------------------------------ */

/** Generated by phone-first signup to satisfy UNIQUE(email). Cannot receive mail. */
const isPlaceholderEmail = (email) =>
  String(email || '').toLowerCase().endsWith('@placeholder.local');

/**
 * Resolve the login identifier to an account.
 *
 * Both steps of the flow go through here so they cannot disagree. If request
 * and verify resolved differently, a code could be mailed to one account and a
 * session issued for another — a broken login at best, account takeover at
 * worst.
 *
 * The address is lower-cased defensively. The zod schema already does this, but
 * this service is also reachable from scripts and future callers, and a
 * case-sensitive UNIQUE column turns a missed toLowerCase() into "your account
 * does not exist".
 */
async function findAccountByEmail(rawEmail) {
  const email = String(rawEmail || '').trim().toLowerCase();
  if (!email) return null;

  return prisma.user.findFirst({
    where: { email, role: { in: ['USER', 'DRIVER'] } },
  });
}

/* ------------------------------------------------------------------ *
 * Request
 * ------------------------------------------------------------------ */

/**
 * Sends a code — but ONLY to addresses that already have an account. This app
 * is registration-gated: an unknown address is refused with NOT_REGISTERED so
 * the client can send the person to sign up first. (This deliberately reveals
 * whether an address is registered, which is the intended product behaviour
 * here. If that ever changes, return a generic reply the way
 * passwordReset.service.js does.)
 */
async function requestOtp(email) {
  const existing = await findAccountByEmail(email);

  if (!existing) {
    throw ApiError.notFound(
      'No account found for this email. Please register first.',
      'NOT_REGISTERED',
    );
  }

  if (!existing.isActive) {
    throw ApiError.forbidden('Your account has been deactivated', 'ACCOUNT_INACTIVE');
  }

  // A phone-first account carries a generated phone_<number>@placeholder.local
  // address. Nothing can be delivered there, so refuse plainly rather than
  // reporting success for a message that will bounce.
  if (isPlaceholderEmail(existing.email)) {
    throw ApiError.badRequest(
      'This account has no usable email address. Please contact support.',
      'NO_EMAIL_ON_ACCOUNT',
    );
  }

  // Keyed by ACCOUNT ID, not by the typed address: the Redis attempt counter,
  // cooldown and daily cap then follow the account, and cannot be reset by
  // varying the spelling of an address or by reaching the same account through
  // a different identifier later.
  const result = await otpService.requestOtp(existing.id, {
    email: existing.email,
    name: existing.name,
  });

  return {
    ...result,
    message: result.sentTo
      ? `A verification code has been sent to ${result.sentTo}`
      : 'A verification code has been sent',
  };
}

/* ------------------------------------------------------------------ *
 * Verify → log in
 * ------------------------------------------------------------------ */

async function verifyAndLogin({ email, code }, meta = {}) {
  const user = await findAccountByEmail(email);

  // Resolved BEFORE the code is checked, because the code is stored under the
  // account id. No account means there is no bucket to check against, so this
  // is reported as an invalid code rather than a missing account — otherwise
  // this step would fail differently for registered and unregistered addresses
  // and become a way to test which ones exist.
  if (!user) {
    throw ApiError.unauthorized('Code is invalid or has expired', 'OTP_INVALID');
  }

  // Throws on wrong/expired/locked. Consumes the code on success.
  await otpService.verifyOtp(user.id, code);

  if (!user.isActive) {
    throw ApiError.forbidden('Your account has been deactivated', 'ACCOUNT_INACTIVE');
  }

  const accessToken = tokens.signAccessToken({ userId: user.id, role: user.role });
  const refreshToken = tokens.signRefreshToken({ userId: user.id });

  await prisma.refreshToken.create({
    data: {
      userId: user.id,
      tokenHash: tokens.hashToken(refreshToken),
      expiresAt: tokens.refreshExpiryDate(),
      userAgent: (meta.userAgent || '').slice(0, 255) || null,
      ip: (meta.ip || '').slice(0, 45) || null,
    },
  });

  return { user: publicUser(user), accessToken, refreshToken };
}

module.exports = { requestOtp, verifyAndLogin };