'use strict';

/**
 * src/services/reportCsv.js   — Day 13
 *
 * Turns a report object (from report.service) into CSV text. Each report has a
 * natural tabular shape; this file is the one place that knows how to flatten
 * each one, so the export job and any future export surface agree on the layout.
 *
 * CSV is generated by hand rather than pulling a library: the escaping rule is
 * small and well-defined (quote a field, double its inner quotes) and a report
 * export has no exotic types. Fewer dependencies, no surprises.
 */

/** RFC-4180 field escaping: quote when the value contains comma, quote, or newline. */
function esc(value) {
  const s = value == null ? '' : String(value);
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

/** rows: array of arrays. Returns CSV text with CRLF line endings. */
function toCsv(rows) {
  return rows.map((r) => r.map(esc).join(',')).join('\r\n');
}

/* ------------------------------------------------------------------ *
 * Per-report flatteners. Each returns { filename, csv }.
 * ------------------------------------------------------------------ */

function executiveCsv(report) {
  const rows = [
    ['Metric', 'Value'],
    ['Window from', report.window.from],
    ['Window to', report.window.to],
    ['Total bookings', report.volume.totalBookings],
    ['Completed', report.volume.completed],
    ['Cancelled', report.volume.cancelled],
    ['Completion rate', report.volume.completionRate],
    ['Cancellation rate', report.volume.cancellationRate],
    ['Distinct customers', report.volume.distinctCustomers],
    ['Gross revenue', report.revenue.grossRevenue],
    ['Commission earned', report.revenue.commissionEarned],
    ['Driver payout', report.revenue.driverPayout],
    ['Welfare levy', report.revenue.welfareLevy],
    ['Refunds', report.revenue.refunds],
    ['Net to platform', report.revenue.netToPlatform],
    ['Avg fare per trip', report.revenue.avgFarePerTrip],
    ['Cash collected', report.cash.collected],
    ['Payment count', report.cash.paymentCount],
  ];
  return { filename: 'executive-report.csv', csv: toCsv(rows) };
}

function fleetCsv(report) {
  const rows = [['Vehicle class', 'Trips', 'Vehicles used', 'Revenue', 'Revenue per vehicle']];
  for (const c of report.byClass) {
    rows.push([c.vehicleClass, c.trips, c.vehiclesUsed, c.revenue, c.revenuePerVehicle]);
  }
  rows.push([]);
  rows.push(['Fleet total', report.fleet.total]);
  rows.push(['Fleet active', report.fleet.active]);
  rows.push(['Vehicles used', report.fleet.vehiclesUsed]);
  rows.push(['Utilisation', report.fleet.utilisation]);
  rows.push(['Total trips', report.totals.trips]);
  return { filename: 'fleet-report.csv', csv: toCsv(rows) };
}

function driverCsv(report) {
  const rows = [
    ['Driver ID', 'Name', 'Completed trips', 'Earnings', 'Rating avg', 'Rating count',
      'Offers received', 'Offers accepted', 'Acceptance rate'],
  ];
  for (const d of report.drivers) {
    rows.push([
      d.driverId, d.name, d.completedTrips, d.earnings, d.ratingAvg, d.ratingCount,
      d.offersReceived, d.offersAccepted, d.acceptanceRate,
    ]);
  }
  return { filename: 'driver-performance-report.csv', csv: toCsv(rows) };
}

function trendCsv(report) {
  const rows = [['Day', 'Bookings', 'Completed', 'Cancelled', 'Revenue']];
  for (const d of report.series) {
    rows.push([d.day, d.bookings, d.completed, d.cancelled, d.revenue]);
  }
  return { filename: 'business-trend-report.csv', csv: toCsv(rows) };
}

function gstCsv(report) {
  const rows = [
    ['Field', 'Value'],
    ['Window from', report.window.from],
    ['Window to', report.window.to],
    ['GST rate %', report.gstRatePct],
    ['SAC code', report.sacCode],
    ['Tax invoice count', report.taxable.invoiceCount],
    ['Taxable value', report.taxable.taxableValue],
    ['CGST', report.taxable.cgst],
    ['SGST', report.taxable.sgst],
    ['IGST', report.taxable.igst],
    ['Total tax', report.taxable.totalTax],
    ['Intra-state tax (CGST+SGST)', report.taxable.intraStateTax],
    ['Inter-state tax (IGST)', report.taxable.interStateTax],
    ['Tax invoice total', report.taxable.invoiceTotal],
    ['Exempt invoice count', report.exempt.invoiceCount],
    ['Exempt total', report.exempt.total],
  ];
  return { filename: 'gst-report.csv', csv: toCsv(rows) };
}

const FLATTENERS = {
  executive: executiveCsv,
  fleet: fleetCsv,
  'driver-performance': driverCsv,
  'business-trend': trendCsv,
  gst: gstCsv,
};

/** Flatten a report object of a given type into { filename, csv }. */
function build(type, report) {
  const fn = FLATTENERS[type];
  if (!fn) throw new Error(`[reportCsv] no CSV layout for "${type}"`);
  return fn(report);
}

module.exports = { build, toCsv, esc };