-- ---------------------------------------------------------------------------
-- ADD THE DISTRICT AREA TIER — THE ENUM VALUE, AND NOTHING ELSE.
-- ---------------------------------------------------------------------------
--
-- A district headquarters has a real fleet presence but is not a metro, and
-- pricing it as either one misrepresents it. Previously such a town had to be
-- filed as TALUKA (overcharging it) or METRO (undercharging it).
--
-- ---------------------------------------------------------------------------
-- WHY THIS MIGRATION CONTAINS ONE STATEMENT
-- ---------------------------------------------------------------------------
-- PostgreSQL will not let a new enum value be USED in the same transaction
-- that creates it:
--
--     ERROR 55P04: unsafe use of new value "DISTRICT" of enum type "AreaTier"
--     HINT: New enum values must be committed before they can be used.
--
-- Prisma wraps each migration in a single transaction, so an ALTER TYPE and an
-- INSERT referencing the new value cannot live in the same file — the INSERT
-- fails, the whole migration rolls back, and the deploy stops with P3018.
-- (That is exactly what happened on the first attempt at this change.)
--
-- The fix is a commit boundary, which is what a migration boundary is. This
-- file adds the value; 20261006121000_tiered_surge_rules, which Prisma runs in
-- its own transaction immediately afterwards, is free to use it.
--
-- DO NOT MERGE THESE TWO FILES BACK TOGETHER. They look like one change and
-- they are, but the split is load-bearing.
--
-- IF NOT EXISTS so a partially-applied or re-run deploy is harmless.
-- ---------------------------------------------------------------------------

ALTER TYPE "AreaTier" ADD VALUE IF NOT EXISTS 'DISTRICT' AFTER 'METRO';