-- The real fleet: 13 models from the client's rate sheet, up to 33 seats.
--
-- WHY MODELS AND NOT SIZE CLASSES
-- ---------------------------------------------------------------------------
-- The rate sheet prices a Swift Dzire differently from an Ertiga, and an Innova
-- 2016 differently from a Crysta 2024. "sedan" and "suv" cannot express that:
-- one price per size bucket is exactly the thing the sheet refuses to do. So
-- each MODEL becomes a vehicleClass, which is what fare_configs, vehicles and
-- rental_packages are all keyed on already. No schema change needed.
--
-- The generic rows seeded by 20260922100000 (hatchback/sedan/suv/luxury/
-- tempo/bus) are left ACTIVE on purpose. fare_configs still prices ONE_WAY,
-- ROUND_TRIP and AIRPORT against them, and retiring them before per-model
-- rates exist would take away every non-rental booking. Retire them from the
-- admin panel once the client supplies per-model outstation rates.

INSERT INTO "vehicle_catalog"
  ("key","name","seats","blurb","detail","luggage","glyph","transmission","fuel","sort_order","updated_at")
VALUES
  ('swift-dzire','Swift Dzire A/C',4,
   'Compact sedan, city and short runs',
   'BSVI 2024. Air-conditioned sedan for one to four passengers. The usual choice for city tours and airport transfers.',
   '2 medium bags','🚗','Manual','Petrol',10, CURRENT_TIMESTAMP),

  ('ertiga','Ertiga A/C',7,
   'Seven seats, compact MPV',
   'BSVI 2025. Seven-seat MPV with air conditioning. Comfortable for a family or a small group with moderate luggage.',
   '3 medium bags','🚙','Manual','Petrol',20, CURRENT_TIMESTAMP),

  ('innova','Innova A/C',8,
   'Eight seats, proven workhorse',
   'BSIV 2016. The long-serving eight-seater. Roomy and reliable for city tours and outstation runs.',
   '4 large bags','🚙','Manual','Diesel',30, CURRENT_TIMESTAMP),

  ('innova-crysta','Innova Crysta A/C',8,
   'Eight seats, premium interior',
   'BSVI 2024. The newer Innova, with a quieter cabin and better seats. Worth the step up on longer journeys.',
   '4 large bags','🚙','Manual','Diesel',40, CURRENT_TIMESTAMP),

  ('innova-hycross','Innova Hycross A/C',8,
   'Eight seats, newest and quietest',
   'BSVI 2026. The latest Innova. The most comfortable eight-seater in the fleet, for client travel and long tours.',
   '4 large bags','🚙','Automatic','Hybrid',50, CURRENT_TIMESTAMP),

  ('tempo-12','Tempo Traveller 12 A/C',12,
   'Twelve seats, group travel',
   'BSVI 2023. Twelve-seat air-conditioned coach for family trips, office outings and temple tours.',
   '12 bags','🚐','Manual','Diesel',60, CURRENT_TIMESTAMP),

  ('urbania-maharaja','Urbania 1x1 Maharaja Luxury',12,
   'Twelve recliners, 1x1 layout',
   'BSVI 2026. Premium Maharaja coach with single-seat-either-side 1x1 recliners. For weddings, VIP travel and long tours where comfort is the point.',
   '12 bags','🚐','Manual','Diesel',70, CURRENT_TIMESTAMP),

  ('urbania-13','Force Urbania 13 A/C',13,
   'Thirteen seats, modern coach',
   'BSVI 2024. Thirteen-seat air-conditioned Urbania. High roof, easy to stand in, comfortable over distance.',
   '13 bags','🚐','Manual','Diesel',80, CURRENT_TIMESTAMP),

  ('urbania-16','Force Urbania 16 A/C',16,
   'Sixteen seats, modern coach',
   'BSVI 2024. The larger Urbania at sixteen seats, for bigger groups needing the same comfort.',
   '16 bags','🚐','Manual','Diesel',90, CURRENT_TIMESTAMP),

  ('tempo-17','Tempo Traveller 17 A/C',17,
   'Seventeen seats, full-day tours',
   'BSVI 2023. Seventeen-seat air-conditioned coach, priced for full twelve-hour days.',
   '17 bags','🚐','Manual','Diesel',100, CURRENT_TIMESTAMP),

  ('benz-22','Bharat Benz 22 Luxury',22,
   'Twenty-two seats, luxury coach',
   'BSVI 2023. Air-conditioned Bharat Benz luxury coach for corporate offsites, pilgrimages and wedding parties.',
   '22 bags','🚌','Manual','Diesel',110, CURRENT_TIMESTAMP),

  ('benz-28','Bharat Benz 28 Luxury',28,
   'Twenty-eight seats, luxury coach',
   'BSVI 2023. The larger Bharat Benz luxury coach, for groups approaching thirty.',
   '28 bags','🚌','Manual','Diesel',120, CURRENT_TIMESTAMP),

  ('benz-33','Bharat Benz 33 Executive',33,
   'Thirty-three seats, executive coach',
   'BSVI 2022. The largest coach offered, in executive trim. For full-size group travel and events.',
   '33 bags','🚌','Manual','Diesel',130, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;


-- Rental packages, for EVERY city.
-- ---------------------------------------------------------------------------
-- The rate sheet came from Hyderabad but the client offers these models across
-- every state on the service list, so the rows are generated by CROSS JOIN
-- against `cities` rather than hardcoding a city id. One INSERT covers however
-- many cities exist today.
--
-- NOTE: a city added LATER gets no packages from this migration. Adding a city
-- must be followed by seeding its packages, or its riders see an empty rental
-- list. Worth doing in the admin flow that creates a city.
--
-- Every package includes 80 km regardless of duration — that is what the sheet
-- says. The 12-hour coaches give twice the time and the same distance.
INSERT INTO "rental_packages"
  ("city_id","vehicle_class","label","included_hours","included_km",
   "package_fare","extra_per_hour","extra_per_km","sort_order")
SELECT c."id", v.vehicle_class, v.label, v.hours, v.km,
       v.fare, v.extra_hour, v.extra_km, v.sort_order
FROM "cities" c
CROSS JOIN (VALUES
  ('swift-dzire',      '8 hrs / 80 km',   8, 80,  2000.00, 150.00, 14.00, 10),
  ('ertiga',           '8 hrs / 80 km',   8, 80,  2500.00, 200.00, 18.00, 20),
  ('innova',           '8 hrs / 80 km',   8, 80,  2500.00, 200.00, 18.00, 30),
  ('innova-crysta',    '8 hrs / 80 km',   8, 80,  3000.00, 250.00, 20.00, 40),
  ('innova-hycross',   '8 hrs / 80 km',   8, 80,  3500.00, 300.00, 25.00, 50),
  ('tempo-12',         '12 hrs / 80 km', 12, 80,  5000.00, 250.00, 27.00, 60),
  ('urbania-maharaja', '8 hrs / 80 km',   8, 80,  8000.00, 400.00, 40.00, 70),
  ('urbania-13',       '8 hrs / 80 km',   8, 80,  7000.00, 300.00, 35.00, 80),
  ('urbania-16',       '8 hrs / 80 km',   8, 80,  7500.00, 350.00, 40.00, 90),
  ('tempo-17',         '12 hrs / 80 km', 12, 80,  6000.00, 300.00, 33.00, 100),
  ('benz-22',          '12 hrs / 80 km', 12, 80,  9000.00, 400.00, 50.00, 110),
  ('benz-28',          '12 hrs / 80 km', 12, 80,  9500.00, 500.00, 55.00, 120),
  ('benz-33',          '12 hrs / 80 km', 12, 80, 10000.00, 500.00, 58.00, 130)
) AS v(vehicle_class, label, hours, km, fare, extra_hour, extra_km, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM "rental_packages" rp
  WHERE rp."city_id" = c."id" AND rp."vehicle_class" = v.vehicle_class
);


-- HOURLY fare cards, for every city.
-- ---------------------------------------------------------------------------
-- A rental still needs a fare_config row: quote.service looks one up by
-- (city, class, HOURLY) BEFORE it reads the package, and throws
-- FARE_CONFIG_MISSING without it. That is what stopped airport trips working.
--
-- hourly_rate is the sheet's extra-hour rate and per_km its extra-km rate, so
-- the flexible "any hours" option and the overage on a fixed package price
-- consistently. minimum_fare is one extra hour — a floor, never the trip price.
INSERT INTO "fare_configs"
  ("city_id","vehicle_class","trip_type","base_fare","per_km","minimum_fare",
   "hourly_rate","hourly_km_per_hour","effective_from")
SELECT c."id", v.vehicle_class, 'HOURLY', 0, v.extra_km, v.extra_hour,
       v.extra_hour, 10, TIMESTAMP '2020-01-01 00:00:00'
FROM "cities" c
CROSS JOIN (VALUES
  ('swift-dzire',      150.00, 14.00),
  ('ertiga',           200.00, 18.00),
  ('innova',           200.00, 18.00),
  ('innova-crysta',    250.00, 20.00),
  ('innova-hycross',   300.00, 25.00),
  ('tempo-12',         250.00, 27.00),
  ('urbania-maharaja', 400.00, 40.00),
  ('urbania-13',       300.00, 35.00),
  ('urbania-16',       350.00, 40.00),
  ('tempo-17',         300.00, 33.00),
  ('benz-22',          400.00, 50.00),
  ('benz-28',          500.00, 55.00),
  ('benz-33',          500.00, 58.00)
) AS v(vehicle_class, extra_hour, extra_km)
WHERE NOT EXISTS (
  SELECT 1 FROM "fare_configs" fc
  WHERE fc."city_id" = c."id"
    AND fc."vehicle_class" = v.vehicle_class
    AND fc."trip_type" = 'HOURLY'
);